# Minimal Aerospace config for testing
after-login-command = []
after-startup-command = []
start-at-login = false

# Remove all integrations that could cause conflicts
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = []

# Basic normalization only
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Test with very small padding
accordion-padding = 0

# Basic layout
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

# Minimal gaps
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

# Essential keybindings only
[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']